# Generated by Django 2.1 on 2018-10-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pincode',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
