# Generated by Django 2.1 on 2018-10-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pincode',
        ),
    ]
